spring.application.name=findporn

# --- RUTAS DE DISCO ---
app.storage.videos.ruta=C:/Proyectos Java/RecibidorVideos/
app.storage.frames.ruta=C:/proyectos Java/Fotogramas/
app.storage.audios.ruta=C:/proyectos Java/Fotogramas/


# --- PROMPTS DE LA IA (Nombres corregidos para coincidir con Java) ---
app.ia.prompts.resumen-fotogramas=Sos un experto analizando videos. Lee esta secuencia cronológica de un video y redactame un resumen corto de lo que ocurre:
app.ia.prompts.frame=Describí con mucho detalle lo que se ve en esta imagen en una sola oración.
app.ia.prompts.audio=Escuchá atentamente este audio extraído de un video. Hacé una transcripción de los diálogos más importantes y describí brevemente si hay sonidos clave (música de tensión, explosiones, risas).
app.ia.prompts.video-completo=Sos el analista final de un sistema de moderación de contenido. A continuación, te proporciono un análisis visual y un análisis de audio extraídos de un mismo video. Cruzá ambas fuentes de información y redactá una conclusión definitiva detallando qué sucede exactamente en el video y de qué trata.

# --- URLs DE LA IA (Sin comillas) ---
app.ia.string.url-fotogramas=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
app.ia.string.url-frame=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
app.ia.string.url-audio=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
app.ia.string.url-videocompleto=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=

google.gemini.api.key=AQ.Ab8RN6JtTZfDYvI181FgeZ7xvFT--rAw8b6hqekLSg84uoUFYw